/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong03.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong03.coffeelogic.coffeeshop;
import lthdt.chuong03.coffeelogic.manager;

/**
 *
 * @author ttysa
 */
public class mycoffee extends javax.swing.JInternalFrame {   
    manager[] managers;
    /**
     * Creates new form mycoffee
     */
    public mycoffee() throws ParseException {
        initComponents();
        
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        coffeeshop[] a = new coffeeshop[]{new coffeeshop("Kha Coffee", "2 Nguyen Trai"),
                                          new coffeeshop("White Coffee", "42 Nguyen Hue"),
                                          new coffeeshop("red Coffee", "92 Nguyen Trai")};
        managers = new manager[]{
                            new manager(a, 100, "Nguyen Van A", 0, df.parse("12-12-1999")),
                            new manager( new coffeeshop[]{
                                                new coffeeshop("Hoang Hac", "35 Nguyen Hue")
                                        },
                                        2000,"Nguyen Van B", 1, df.parse("12-12-1999"))
                            };
        for(int i = 0; i < managers.length; i++) {
            cbQL.addItem(managers[i].getHoten());
        }
        
        DefaultTableModel model = (DefaultTableModel)tblCoffeeshop.getModel();
        model.setRowCount(0);
        coffeeshop[] shops = managers[0].getShops();
        for(int i = 0; i < shops.length; i++) {
            model.insertRow(model.getRowCount(),
                    new Object[]{model.getRowCount() + 1,
                    shops[i].getName(),
                    shops[i].getAddress()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbQL = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCoffeeshop = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh sach cac quan coffee");

        jLabel1.setText("Ho ten nguoi quan ly");

        cbQL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQLItemStateChanged(evt);
            }
        });

        tblCoffeeshop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ten quan", "Dia chi"
            }
        ));
        jScrollPane1.setViewportView(tblCoffeeshop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbQL, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbQL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbQLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQLItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblCoffeeshop.getModel();
        model.setRowCount(0);
        int index = cbQL.getSelectedIndex();
        coffeeshop[] shops = managers[index].getShops();
        for(int i = 0; i < shops.length; i++) {
            model.insertRow(model.getRowCount(),
                    new Object[]{model.getRowCount() + 1,
                    shops[i].getName(),
                    shops[i].getAddress()});
        }
    }//GEN-LAST:event_cbQLItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbQL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCoffeeshop;
    // End of variables declaration//GEN-END:variables
}
