/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lthdt.chuong03.dohoa.frames;

import java.awt.Graphics2D;
import java.util.Random;

/**
 *
 * @author ttysa
 */
public class XuaDLFrame extends javax.swing.JInternalFrame {
    int[] a;

    /**
     * Creates new form XuaDLFrame
     */
    public XuaDLFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPanel = new javax.swing.JPanel();
        btnVe = new javax.swing.JButton();
        btnSapxep = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Ve du lieu mang 1 chieu");

        javax.swing.GroupLayout pnPanelLayout = new javax.swing.GroupLayout(pnPanel);
        pnPanel.setLayout(pnPanelLayout);
        pnPanelLayout.setHorizontalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        pnPanelLayout.setVerticalGroup(
            pnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        btnVe.setText("Ve mang 1 chieu ra man hinh");
        btnVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeActionPerformed(evt);
            }
        });

        btnSapxep.setText("Sap xep mang 1 chieu");
        btnSapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVe)
                    .addComponent(btnSapxep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSapxep, btnVe, pnPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSapxep)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnPanel.getGraphics();
        int maxX = pnPanel.getWidth();
        int maxY = pnPanel.getHeight();
        int step = 5;
        int n = maxX/step;
        int[] a = new int[n];
        Random rnd = new Random();
        for(int i = 0; i < n; i++){
            a[i] = rnd.nextInt(maxY);
        }
        int beginX = 0, beginY = 0;
        gr.clearRect(0, 0, maxX, maxY);
        for(int i = 0; i < n; i++){
//            gr.drawRect(beginX, beginY, step, a[i]);
            gr.drawRect(beginX, maxY - a[i], step, a[i]);
            beginX += step;
        }
        
    }//GEN-LAST:event_btnVeActionPerformed

    private void btnSapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxepActionPerformed
        // TODO add your handling code here:
        Graphics2D gr = (Graphics2D) pnPanel.getGraphics();
        int maxX = pnPanel.getWidth();
        int maxY = pnPanel.getHeight();
        int step = 5;
        int n = maxX/step;
        int beginX = 0, beginX2 = 0;
        for(int i = 0; i < n - 1; i++){
            for(int j = i + 1; j < n; j++) {
                if(a[i] > a[j]) {
                    int temp = a[i];
                    // Xoa hinhf a[i] cu
                    gr.clearRect(beginX, maxY - a[i], step, a[i]);
                    // Ve hinh a[i] moi
                    a[i] = a[j];
                    gr.drawRect(beginX, maxY - a[i], step, a[i]);
                    // Xoa hinh a[j] cu
                    beginX2 = j*step;
                    gr.clearRect(beginX2, maxY - a[j], step, a[j]);
                    // Ve hinh a[j] moi
                    a[j] = temp;
                    gr.drawRect(beginX2, maxY - a[j], step, a[j]);
                    
                }
            }
            beginX += step;
        }
    }//GEN-LAST:event_btnSapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSapxep;
    private javax.swing.JButton btnVe;
    private javax.swing.JPanel pnPanel;
    // End of variables declaration//GEN-END:variables
}
